server:
  port: 7181
spring:
  application:
    name: redm-eureka-server
eureka:
  client:
    # \u662F\u5426\u6CE8\u518C
    register-with-eureka: false
    # \u662F\u5426\u62C9\u53D6\u6CE8\u518C\u8868
    fetch-registry: false
    # 服务端 url
    service-url:
      defaultZone: http://192.168.215.119:7181/eureka