server:
  port: 7181
spring:
  application:
    name: redm-eureka-server
eureka:
  client:
    # 是否注册
    register-with-eureka: false
    # 是否拉取注册表
    fetch-registry: false
    # 服务端 url
    service-url:
      defaultZone: http://192.168.215.119:7181/eureka