server:
  port: 7181
spring:
  application:
    name: redm-eureka-server
eureka:
  client:
    # 不注册到注册中心
    register-with-eureka: false
    # 不拉取注册表
    fetch-registry: false
    # 注册中心地址
    service-url:
      defaultZone: http://192.168.215.119:7181/eureka
