server:
  port: 5815
spring:
  application:
    name: redm-gateway
  cloud:
    gateway:
      discovery:
        # 基于服务注册信息自动构建路由
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    # 注册到注册中心
    register-with-eureka: true
    # 拉取注册表
    fetch-registry: true
    # 注册中心地址
    service-url:
      defaultZone: http://192.168.215.119:7181/eureka
