server:
  port: 5815
spring:
  application:
    name: redm-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启基于服务注册表创建路由
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    # 是否注册
    register-with-eureka: true
    # 是否拉取注册表
    fetch-registry: true
    # 服务端 url
    service-url:
      defaultZone: http://192.168.215.119:7181/eureka